apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
nameSuffix: -frontend
commonLabels:
  role: frontend
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: podinfo
  spec:
    template:
      spec:
        containers:
        - name: podinfod
          env:
          - name: PODINFO_BACKEND_URL
            value: http://podinfo-backend:9898/echo
          - name: PODINFO_OTEL_SERVICE_NAME
            value: podinfo-frontend
